# Generated by Django 3.1.14 on 2024-03-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20240301_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolved_pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon'),
        ),
    ]
