# Generated by Django 3.1.14 on 2024-03-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_pokemon_evolved_pokemon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='evolved_pokemon',
            new_name='next_evolution',
        ),
    ]
